### ISSUE TITLE
why use /var/run/netns? 

### ISSUE THREAD

**Issue by gaorong** [eranyanay/cni-from-scratch#2]
Thanks for the great presentation! I watched on youtube and there was a step that I couldn't yet understand. 

why would you prefer /var/run/nets than /proc/$PID/ns/net? 
as code write here:
https://github.com/eranyanay/cni-from-scratch/blob/92f788dfb66f6f1cf36b140929fe9d2e9a276863/my-cni-demo#L32

could you tell a little bit more about this?

**Comment by eranyanay** [comment]
I need it to exist under `/var/run/netns` in order to manage it using the `ip netns` tool

**Comment by gaorong** [comment]
Thanks a lot, I got it!
After digging into this, I find it would be safer to use `mount --bind /proc/$PID/ns/net /var/run/netns/$CNI_CONTAINERID`. when the original container dies or is removed, the net namespace can still remain to manipulate. Is this wanted? WDYT?

**Comment by eranyanay** [comment]
I guess it depends on the use case and implementation, here I show a simple approach which doesnt need any manipulation after container is stopped
I guess that in more advanced cases there might be some post operations that you want to do, some cleanup, or maybe inform some component in your CNI implementation that an IP is freed,  for example, and then it makes sense to mount the network namespace differently in order to perform cleanup

But note that the CNI interface also declares the `DEL` command (see [here](https://github.com/containernetworking/cni/blob/master/SPEC.md)) which more or less covers what I just said

**Comment by gaorong** [comment]
Yes, I agree. thanks very much for explaining.
